import {MintBNOTE} from "@/components/bnote/MintBNOTE.tsx";
import {useSetLayoutData} from "@/hooks/useSetLayoutData.tsx";

export function MintBNOTEPage() {
    useSetLayoutData({
        title: 'Bittrees Research Preferred Stock',
        showBackButton: true,
        backButtonText: 'Member Services',
        backButtonTo: '/members'
    });

    return (
        <div className="flex flex-col gap-3 p-4 md:p-12 items-center">
            <div className="mx-auto flex flex-col items-center max-w-md drop-shadow-xl">
                <h1 className="text-3xl font-newtimesroman mb-3">BNOTE</h1>
                <img
                    src={`/bnote-certificate.jpeg`}
                    width="1090px"
                    height="612px"
                    alt="BNOTE Preferred Stock"
                />
            </div>
            <div className="mt-4 mb-4">
                <MintBNOTE/>
            </div>
            {/* <div className="space-y-5 mt-8 text-left mx-8 font-newtimesroman">
            <div>
              <hr className="border-gray-500" />
            </div>
            <p className="font-bold">
              Disclaimer for BRGOV Tokens:
              <br />
              <br />
              Please read this disclaimer carefully before purchasing or
              acquiring BRGOV tokens. By purchasing or acquiring BRGOV tokens,
              you acknowledge and agree to the following:
            </p>
            <p>
              <span className="font-bold">Nature of BRGOV Tokens:</span> BRGOV
              tokens are non-fungible tokens (NFTs) issued by Bittrees Research.
              These tokens represent preferred stock certificates in Bittrees
              Research and entitle the holders to limited voting rights as
              outlined in this disclaimer. BRGOV tokens do not grant any
              ownership rights or equity in Bittrees Research beyond the
              specified limited voting rights.
            </p>
            <p>
              <span className="font-bold">Voting Rights:</span> Holders of BRGOV
              tokens are granted voting rights solely for the purpose of
              approving budget proposals submitted by members of Bittrees
              Research. These voting rights are limited to the budget approval
              process and do not extend to other aspects of the organization or
              its governance.
            </p>
            <p>
              <span className="font-bold">Purchase Price:</span> BRGOV tokens
              can be acquired by exchanging 1000 BTREE tokens or 0.001 WBTC
              tokens. The purchase price is fixed and non-negotiable.
            </p>
            <p>
              <span className="font-bold">Non-Expiry:</span> BRGOV tokens do not
              have an expiration date. Once acquired, they will remain in your
              possession indefinitely.
            </p>
            <p>
              <span className="font-bold">Dividends:</span> BRGOV token holders
              should not expect any dividends or profit-sharing arrangements
              from Bittrees Research. BRGOV tokens do not confer any entitlement
              to dividends or profits generated by Bittrees Research.
            </p>
            <p>
              <span className="font-bold">Risks:</span> The purchase and
              ownership of BRGOV tokens involve certain risks. The value of
              BRGOV tokens may fluctuate based on various factors, including
              market conditions and the performance of Bittrees Research. It is
              important to carefully consider these risks and to conduct your
              own research before acquiring BRGOV tokens.
            </p>
            <p>
              <span className="font-bold">No Guarantee of Outcome:</span>{" "}
              Bittrees Research makes no guarantees or representations regarding
              the outcome, success, or future performance of the organization or
              its projects. The acquisition of BRGOV tokens does not guarantee
              any specific benefits or returns.
            </p>

            <p>
              <span className="font-bold">
                By proceeding with the acquisition of BRGOV tokens, you
                acknowledge that you have read, understood, and agreed to the
                terms and conditions set forth in this disclaimer. If you do not
                agree with any part of this disclaimer, you should refrain from
                acquiring BRGOV tokens.
              </span>
            </p>
          </div> */}
        </div>
    );
}
